# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3519a6e8e1f49f42e0d4d9680535b88661936430354e4c5c2a89952772f33de36f99e94ba8ddaf8984c983d8a3bf36a34fef59d2ffab18321fd53fc2ff10c4e2

test:
  secret_key_base: 25e80b3ae08785251cae8d4fb2ef8cfc82c22323c29509927a34caf57d1482312ae2e01acb0e3b78a483c34257510a02a02af8b34c7e095fe8f108e9dcf22a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
